import { Client } from './types';

const now = () => new Date().toISOString();
const daysAgo = (n: number) => { const d = new Date(); d.setDate(d.getDate() - n); return d.toISOString(); };
const daysFromNow = (n: number) => { const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString(); };

export const demoData: Client[] = [
  {
    id: 'demo-1',
    company_name: 'Polara Bibite',
    sector: 'Beverage',
    type: 'Azienda',
    city: 'Modica',
    website: 'https://polara.it',
    instagram_url: 'https://instagram.com/bibitepolara',
    priority: 'Alta',
    revenue: '€ 15.297.882',
    has_vat: false,
    status: 'In trattativa',
    notes: 'TOP CLIENT. Bottiglie di vetro vintage, liquidi colorati. Perfetto per spot 3D stile Coca-Cola. Il 3D si trasforma in asset riutilizzabile, ROI elevatissimo.',
    concept_idea: 'Spot cinematografico in slow motion: bottiglia ghiacciata, liquido che si versa, colori che esplodono. Estetica estate siciliana anni \'60.',
    tags: ['premium', 'beverage', 'spot', 'priorità-alta'],
    contacts: [
      {
        id: 'demo-1-c1',
        client_id: 'demo-1',
        name: 'Giuseppe Polara',
        role: 'Business Development & Marketing',
        email: 'giuseppe@polara.it',
        phone: '+39 0932 000001',
        is_primary: true,
        notes: 'Contatto principale. Risponde rapidamente su email.',
      },
      {
        id: 'demo-1-c2',
        client_id: 'demo-1',
        name: 'Maria Cannizzaro',
        role: 'Marketing Manager',
        email: 'marketing@polara.it',
        is_primary: false,
      },
    ],
    interactions: [
      {
        id: 'demo-1-i1',
        client_id: 'demo-1',
        date: daysAgo(14),
        type: 'Email',
        contact_id: 'demo-1-c1',
        subject: 'Proposta spot 3D bottiglie estate',
        body: 'Ho inviato email di presentazione con moodboard allegato. Concept: slow motion estivo, palette calda, estetica anni \'60.',
        outcome: 'Risposta positiva',
        next_action: 'Inviare proposta economica dettagliata',
        next_action_date: daysFromNow(2),
      },
      {
        id: 'demo-1-i2',
        client_id: 'demo-1',
        date: daysAgo(7),
        type: 'Chiamata',
        contact_id: 'demo-1-c1',
        subject: 'Call di allineamento sul concept',
        body: 'Chiamata di 30 minuti. Molto interessati al progetto. Vogliono vedere una previz prima di confermare il budget.',
        outcome: 'Da seguire',
        next_action: 'Preparare animatic / previz del concept',
        next_action_date: daysFromNow(5),
      },
    ],
    files: [
      {
        id: 'demo-1-f1',
        client_id: 'demo-1',
        name: 'Moodboard Polara Estate',
        description: 'Riferimenti visivi per lo spot estivo',
        url: 'https://drive.google.com',
        type: 'Moodboard',
        created_at: daysAgo(15),
      },
    ],
    timeline: [
      { id: 'demo-1-t1', client_id: 'demo-1', date: daysAgo(14), type: 'interaction', description: 'Email: Proposta spot 3D bottiglie estate' },
      { id: 'demo-1-t2', client_id: 'demo-1', date: daysAgo(7), type: 'interaction', description: 'Chiamata: Call di allineamento sul concept' },
    ],
    created_at: daysAgo(20),
    updated_at: daysAgo(7),
  },
  {
    id: 'demo-2',
    company_name: 'Sabadì',
    sector: 'Food',
    type: 'Azienda',
    city: 'Modica',
    website: 'https://sabadi.it',
    instagram_url: 'https://instagram.com/ilgiornocheforsenonesiste',
    priority: 'Alta',
    revenue: '€ 1.763.753',
    has_vat: false,
    status: 'Contattato',
    notes: 'Hanno i packaging più belli della Sicilia. Fondatore con forte identità personale e senso estetico. Approccio diretto, da creativo a creativo.',
    concept_idea: 'Animazione 3D in cui la carta del packaging si apre magicamente rivelando il cioccolato dentro. Stile sognante, quasi stop motion.',
    tags: ['packaging', 'food', 'premium', 'cioccolato'],
    contacts: [
      {
        id: 'demo-2-c1',
        client_id: 'demo-2',
        name: 'Simone Sabaini',
        role: 'Fondatore & CEO',
        email: 'simone@sabadi.it',
        instagram_url: 'https://instagram.com/simonesabaini',
        is_primary: true,
        notes: 'Fondatore visionario, molto presente sui social. DM su Instagram può funzionare meglio della email.',
      },
    ],
    interactions: [
      {
        id: 'demo-2-i1',
        client_id: 'demo-2',
        date: daysAgo(5),
        type: 'Instagram DM',
        contact_id: 'demo-2-c1',
        subject: 'Primo contatto via DM',
        body: 'Messaggio diretto su Instagram con concept sintetico dell\'idea packaging animation. Tono da creativo a creativo.',
        outcome: 'In attesa',
        next_action: 'Follow-up se non risponde entro una settimana',
        next_action_date: daysFromNow(2),
      },
    ],
    files: [],
    timeline: [
      { id: 'demo-2-t1', client_id: 'demo-2', date: daysAgo(5), type: 'interaction', description: 'Instagram DM: Primo contatto via DM' },
    ],
    created_at: daysAgo(6),
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-3',
    company_name: 'Caffè Moak',
    sector: 'Caffè',
    type: 'Azienda',
    city: 'Modica',
    website: 'https://caffemoak.com',
    instagram_url: 'https://instagram.com/caffemoak',
    priority: 'Alta',
    revenue: '€ 24.536.413',
    has_vat: false,
    status: 'Da contattare',
    notes: 'Estetica molto "advertising anni \'60". Budget alto. L\'Art Director interno è il contatto giusto — parla già il linguaggio creativo.',
    concept_idea: 'Motion graphics stilizzata in stile retrò-moderno. Palette marrone/oro/crema. Sequenza di preparazione del caffè come rituale.',
    tags: ['caffè', 'motion', 'retrò', 'budget-alto'],
    contacts: [
      {
        id: 'demo-3-c1',
        client_id: 'demo-3',
        name: 'Marco Lentini',
        role: 'Art Director',
        email: 'marco.lentini@caffemoak.com',
        is_primary: true,
        notes: 'Art Director interno. È il contatto più rilevante — approccio da AD a AD.',
      },
      {
        id: 'demo-3-c2',
        client_id: 'demo-3',
        name: 'Annalisa Spadola',
        role: 'Chief Marketing Officer',
        email: 'annalisa.spadola@caffemoak.com',
        is_primary: false,
      },
    ],
    interactions: [],
    files: [],
    timeline: [],
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-4',
    company_name: 'Campo d\'Oro',
    sector: 'Food',
    type: 'Azienda',
    city: 'Sciacca',
    website: 'https://campodoro.com',
    instagram_url: 'https://instagram.com/campodoro.srl',
    priority: 'Alta',
    revenue: '€ 9.004.799',
    has_vat: false,
    status: 'Proposta inviata',
    notes: 'Export in USA e Dubai. La loro linea Villa Reale Supreme vince premi per design e qualità. Comunicare il lusso visivamente.',
    concept_idea: 'Cinematic product reveal dell\'olio Villa Reale Supreme. Luce calda, texture olive, bottiglia premium in slow motion. Tono: lusso mediterraneo.',
    tags: ['olio', 'luxury', 'export', 'premium'],
    contacts: [
      {
        id: 'demo-4-c1',
        client_id: 'demo-4',
        name: 'Licata',
        role: 'CEO & Founder',
        email: 'licata@campodoro.com',
        is_primary: true,
      },
    ],
    interactions: [
      {
        id: 'demo-4-i1',
        client_id: 'demo-4',
        date: daysAgo(10),
        type: 'Email',
        contact_id: 'demo-4-c1',
        subject: 'Proposta visual storytelling Villa Reale Supreme',
        body: 'Email con proposta completa: concept creativo, processo di lavoro, timeline e preventivo. Allegato PDF con moodboard.',
        outcome: 'In attesa',
        next_action: 'Follow-up se non risponde',
        next_action_date: daysFromNow(-1),
      },
    ],
    files: [
      {
        id: 'demo-4-f1',
        client_id: 'demo-4',
        name: 'Proposta Campo d\'Oro',
        description: 'PDF con concept, processo e preventivo',
        url: 'https://drive.google.com',
        type: 'Proposta',
        created_at: daysAgo(10),
      },
    ],
    timeline: [
      { id: 'demo-4-t1', client_id: 'demo-4', date: daysAgo(10), type: 'interaction', description: 'Email: Proposta visual storytelling Villa Reale Supreme' },
    ],
    created_at: daysAgo(12),
    updated_at: daysAgo(10),
  },
  {
    id: 'demo-5',
    company_name: 'Boma Studio',
    sector: 'Agenzia',
    type: 'Agenzia/Studio',
    city: 'Modica',
    website: 'https://bomastudio.it',
    instagram_url: 'https://instagram.com/bomastudio',
    priority: 'Alta',
    revenue: '€ 242.104',
    has_vat: false,
    status: 'Cliente attivo',
    notes: 'Agenzia creativa locale. Non hanno 3D Artist interni. Canale ideale per accedere a brief reali con budget reali. Collaborazione in corso.',
    concept_idea: 'Posizionarsi come partner 3D esterno di fiducia. Proporre una tariffa giornaliera preferenziale in cambio di volume e continuità.',
    tags: ['agenzia', 'collaborazione', 'partner', 'attivo'],
    contacts: [
      {
        id: 'demo-5-c1',
        client_id: 'demo-5',
        name: 'Andrea Baglieri',
        role: 'CEO & Art Director',
        email: 'andreabaglieri@bomastudio.it',
        is_primary: true,
      },
      {
        id: 'demo-5-c2',
        client_id: 'demo-5',
        name: 'Gloria',
        role: 'Account',
        email: 'gloria@bomastudio.it',
        is_primary: false,
      },
    ],
    interactions: [
      {
        id: 'demo-5-i1',
        client_id: 'demo-5',
        date: daysAgo(30),
        type: 'Incontro',
        contact_id: 'demo-5-c1',
        subject: 'Incontro presentazione collaborazione',
        body: 'Incontro di persona. Molto interesse per una collaborazione continuativa su progetti 3D.',
        outcome: 'Risposta positiva',
        next_action: 'Inviare disponibilità per il progetto Agromonte',
        next_action_date: daysFromNow(3),
      },
    ],
    files: [],
    timeline: [
      { id: 'demo-5-t1', client_id: 'demo-5', date: daysAgo(30), type: 'interaction', description: 'Incontro: Presentazione collaborazione' },
    ],
    created_at: daysAgo(35),
    updated_at: daysAgo(30),
  },
];
